---
galaxy_info:
  role_name: disable_account
  description: Disable a local account on EL 8/9 (lock, expire, nologin shell), revoke SSH keys, remove crontab and sudoers, optionally kill processes.
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["8", "9"]
dependencies: []

