---
- hosts: all
  tasks:
    - name: Copy new config in yum.conf - EL7
      ansible.builtin.copy:
        src: yum_7_exludes.conf
        dest: /etc/yum.conf
        owner: root
        group: root
        mode: '0644'
        validate_certs: false
      when: ansible_distribution_major_version == '7'
    
    - name: Copy new config in dnf.conf - EL8
      ansible.builtin.copy:
        src: yum_8_exludes.conf
        dest: /etc/dnf/dnf.conf
        owner: root
        group: root
        mode: '0644'
        validate_certs: false
      when: ansible_distribution_major_version == '8'
    
    - name: Copy new config in dnf.conf - EL9
      ansible.builtin.copy:
        src: yum_9_exludes.conf
        dest: /etc/dnf/dnf.conf
        owner: root
        group: root
        mode: '0644'
        validate_certs: false
      when: ansible_distribution_major_version == '9'

    - name: Update without packages that need reboot - EL7
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: kernel*,*-firmware-*,glibc*,linux-firmware,dbus*,systemd*,systemd-*,udev,hal,java*,libgudev1*,openssl*,nscd*,kmod*,libnsl*
      when: ansible_distribution_major_version == '7'

    - name: Update without packages that need reboot - EL8
      ansible.builtin.dnf:
        name: '*'
        state: latest
        exclude: kernel*,*-firmware-*,glibc*,linux-firmware,dbus*,systemd*,systemd-*,udev,hal,java*,kmod*,libnsl*
      when: ansible_distribution_major_version == '8'
    
    - name: Update without packages that need reboot - EL9
      ansible.builtin.dnf:
        name: '*'
        state: latest
        exclude: kernel*,*-firmware-*,glibc*,linux-firmware,dbus*,systemd*,systemd-*,udev,hal,java*,kmod*,libnsl*
      when: ansible_distribution_major_version == '9'
