---
galaxy_info:
  role_name: create_user
  description: Create or remove a local user on EL 8/9, with groups, sudoers, password/lock, and authorized_keys.
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["8", "9"]
dependencies: []
