---
galaxy_info:
  role_name: manage_packages
  description: Manage packages on RHEL-like systems (install/upgrade, remove, pin versions, cache update).
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["8", "9"]
dependencies: []

  
