---
galaxy_info:
  role_name: install_node_exporter
  description: Install and run Prometheus node_exporter via systemd on EL 8/9.
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions: ["8", "9"]
dependencies: []

  
