---
- name: Clean up old files
  hosts: "{{ target_host }}"
  become: true
  vars:
    age_days: 7
    max_file_size_mb: 500
    file_patterns:
      - "*.log"
      - "*.tmp"
      - "*.bak"
      - "*.old"
  tasks:
    - name: Ensure target path exists
      ansible.builtin.stat:
        path: "{{ target_path }}"
      register: path_info
      failed_when: not path_info.stat.exists

    - name: Find old files
      ansible.builtin.find:
        paths: "{{ target_path }}"
        patterns: "{{ file_patterns }}"
        age: "{{ age_days }}d"
        recurse: true
        file_type: file
        size: "<{{ max_file_size_mb }}m"
      register: old_files

    - name: Remove files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_files.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Report deleted files
      ansible.builtin.debug:
        msg: "Deleted: {{ item.path }}"
      loop: "{{ old_files.files }}"
      when: old_files.files | length > 0
