---
- name: Enable Satellite Client repo and install SCAP client
  hosts: all
  become: true
  tasks:
    - name: Enable Satellite Client repository
      command: >
        subscription-manager repos --enable=satellite-client-6-for-rhel-{{ ansible_distribution_major_version }}-x86_64-rpms
      register: repo_status
      changed_when: "'is enabled' in repo_status.stdout"

    - name: Install rubygem-foreman_scap_client
      yum:
        name: rubygem-foreman_scap_client
        state: present

    - name: Install Katello host tools
      yum:
        name: katello-host-tools
        state: present
